"""月次一括勤怠アクションで共有する定数です。"""

BULK_ATTENDANCE_API_WAIT_SECONDS = 0.5
BULK_ATTENDANCE_PAID_HOLIDAYS_PAGE_LIMIT = 100

BULK_ATTENDANCE_WORK_START_MINUTES = 9 * 60
BULK_ATTENDANCE_WORK_END_MINUTES = 19 * 60

BULK_ATTENDANCE_BREAK_START_TIME = "11:30:00"
BULK_ATTENDANCE_BREAK_END_TIME = "12:30:00"

BULK_ATTENDANCE_ALLOWED_PAID_HOLIDAY_STATUSES = ("approved", "in_progress")
